const ACTIVITY_TYPES = ["mission", "project"] as const;

const MISSION_KINDS = ["hourly_rate", "daily_rate", "flat rate"] as const;

const PROJECT_KINDS = ["paid", "free"] as const;

const DEFAULT_NUMBER_OF_HOURS_WORKED_PER_DAY = 7;
const DEFAULT_NUMBER_DAYS_WORKED_PER_WEEKS = 5;
const DEFAULT_NUMBER_OF_DAYS_OFF_PER_YEAR =
  8 * DEFAULT_NUMBER_DAYS_WORKED_PER_WEEKS;

export {
  ACTIVITY_TYPES,
  MISSION_KINDS,
  PROJECT_KINDS,
  DEFAULT_NUMBER_OF_HOURS_WORKED_PER_DAY,
  DEFAULT_NUMBER_DAYS_WORKED_PER_WEEKS,
  DEFAULT_NUMBER_OF_DAYS_OFF_PER_YEAR,
};
